# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(forms.models.BaseForm, models.Model),
        ),
        migrations.CreateModel(
            name='SeekerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(forms.models.BaseForm, models.Model),
        ),
        migrations.DeleteModel(
            name='BaseForm',
        ),
    ]
