# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170620_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerform',
            name='text',
        ),
        migrations.RemoveField(
            model_name='seekerform',
            name='text',
        ),
    ]
