# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_auto_20170620_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerform',
            name='aditionalText',
            field=models.TextField(null=True, default=''),
        ),
        migrations.AddField(
            model_name='ownerform',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seekerform',
            name='aditionalText',
            field=models.TextField(null=True, default=''),
        ),
        migrations.AddField(
            model_name='seekerform',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
