# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170620_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerform',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='seekerform',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ownerform',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerform',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
