# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gnuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
